/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import Classes.Application;
import Classes.EXTCLASS;
import Panels.Sign_In;
import Pojos.MyCompanyDetails;
import java.awt.Image;
import javax.swing.ImageIcon;
import org.hibernate.Criteria;
import org.hibernate.criterion.Restrictions;

/**
 *
 * @author Sheha
 */
public class Login extends javax.swing.JFrame {

     static Login login;
    public static String audiioPath = "/Audio/button-3.mp3";

    private Login() {
        initComponents();
        EXTCLASS.setFrameIcon(this);
        EXTCLASS.FrameAdd(new Sign_In(), card_login);
        setCompanyDetails();
        EXTCLASS.createFileinC();

    }

    public static Login getLogin() {
        if (login == null) {
            login = new Login();
        }
        return login;
    }

    public void disposeMe() {

        this.dispose();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        card_login = new javax.swing.JPanel();
        companyLogo = new javax.swing.JLabel();
        companyTp_txt = new javax.swing.JLabel();
        companyName_txt = new javax.swing.JLabel();
        companyAddress_txt = new javax.swing.JLabel();
        companyEmail_txt = new javax.swing.JLabel();
        companyWeb_txt = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        card_login.setLayout(new java.awt.CardLayout());
        jPanel1.add(card_login, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 88, 476, 540));
        jPanel1.add(companyLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 80, 330, 150));

        companyTp_txt.setFont(new java.awt.Font("Nirmala UI", 1, 18)); // NOI18N
        companyTp_txt.setForeground(new java.awt.Color(255, 255, 255));
        companyTp_txt.setText("(+94)75 755 7555");
        jPanel1.add(companyTp_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 600, 490, -1));

        companyName_txt.setFont(new java.awt.Font("Nirmala UI", 1, 24)); // NOI18N
        companyName_txt.setForeground(new java.awt.Color(255, 255, 255));
        companyName_txt.setText("TECHNOGEN SOFTWARES PVT(LTD)");
        jPanel1.add(companyName_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 460, 490, -1));

        companyAddress_txt.setFont(new java.awt.Font("Nirmala UI", 1, 18)); // NOI18N
        companyAddress_txt.setForeground(new java.awt.Color(255, 255, 255));
        companyAddress_txt.setText("Main Street,Colombo 07");
        jPanel1.add(companyAddress_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 510, 490, -1));

        companyEmail_txt.setFont(new java.awt.Font("Nirmala UI", 1, 18)); // NOI18N
        companyEmail_txt.setForeground(new java.awt.Color(255, 255, 255));
        companyEmail_txt.setText("technogen@gmail.com");
        jPanel1.add(companyEmail_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 540, 490, -1));

        companyWeb_txt.setFont(new java.awt.Font("Nirmala UI", 1, 18)); // NOI18N
        companyWeb_txt.setForeground(new java.awt.Color(255, 255, 255));
        companyWeb_txt.setText("www.technogen.com");
        jPanel1.add(companyWeb_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 570, 490, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/login_2.jpg"))); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 730));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                getLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JPanel card_login;
    private javax.swing.JLabel companyAddress_txt;
    private javax.swing.JLabel companyEmail_txt;
    private javax.swing.JLabel companyLogo;
    private javax.swing.JLabel companyName_txt;
    private javax.swing.JLabel companyTp_txt;
    private javax.swing.JLabel companyWeb_txt;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

    boolean isLogoSet = false;
    boolean isComapnyNameSet = false;
    boolean isAddressSet = false;
    boolean isEmailSet = false;
    boolean isWebSiteSet = false;
    boolean isTPSet = false;

    private void setCompanyDetails() {
        try {

            Criteria c = EXTCLASS.getHibSession().createCriteria(MyCompanyDetails.class);
            c.add(Restrictions.eq("status", "active"));

            if (Application.isCompanySet()) {

                MyCompanyDetails company = (MyCompanyDetails) c.uniqueResult();

                if (!company.getName().isEmpty()) {

                    companyName_txt.setText(company.getName());
                } else {
                    companyName_txt.setText("YOUR COMPANY NAME");
                }
                String address = "";
                if (!company.getNo().isEmpty()) {
                    address += company.getNo() + ", ";

                }
                if (!company.getStreet().isEmpty()) {
                    address += company.getStreet() + ", ";

                }
                if (!company.getCity().isEmpty()) {
                    address += company.getCity() + ", ";

                }
                if (!company.getCountry().isEmpty()) {
                    address += company.getCountry() + ".";

                }
                if (!address.isEmpty()) {
                    companyAddress_txt.setText(address);
                } else {
                    companyAddress_txt.setText("YOUR ADDRESS");
                }
                if (!company.getEmail().isEmpty()) {

                    companyEmail_txt.setText(company.getEmail());
                } else {
                    companyEmail_txt.setText("YOUR EMAIL");

                }
                if (!company.getWebsite().isEmpty()) {
                    companyWeb_txt.setText(company.getWebsite());
                } else {

                    companyWeb_txt.setText("YOUR WEBSITE");
                }
                if (!company.getMobile1().toString().isEmpty()) {
                    companyTp_txt.setText(company.getMobile1().toString());
                } else {
                    companyTp_txt.setText("YOUR CONTACT NO");
                }
                if (!company.getImg2().isEmpty() && company.getImg2() != null) {

                    Image img = new ImageIcon(company.getImg2()).getImage();
                    img = img.getScaledInstance(companyLogo.getWidth(), companyLogo.getHeight(), Image.SCALE_SMOOTH);
                    companyLogo.setIcon(new ImageIcon(img));
                } else {
                    System.out.println("no image");
                    ImageIcon i = new ImageIcon(getClass().getResource("/Img/demo_logo_new.png"));
                    companyLogo.setIcon(i);

                }

            } else {
                companyName_txt.setText("YOUR COMPANY NAME");
                companyAddress_txt.setText("YOUR ADDRESS");
                companyEmail_txt.setText("YOUR EMAIL");
                companyWeb_txt.setText("YOUR WEBSITE");
                companyTp_txt.setText("YOUR CONTACT NO");
                ImageIcon i = new ImageIcon(getClass().getResource("/Img/demo_logo_new.png"));
                companyLogo.setIcon(i);
            }

        } catch (Exception e) {
            e.printStackTrace();
        }

    }
}
