/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Panels;

import Classes.Application;
import Classes.EXTCLASS;
import Pojos.MyCompanyDetails;
import java.awt.Color;
import java.awt.Component;
import java.awt.Desktop;
import java.awt.Font;
import java.awt.Image;
import java.io.File;
import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;
import java.util.ArrayList;
import java.util.List;
import java.util.Vector;
import javax.imageio.ImageIO;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.border.SoftBevelBorder;
import javax.swing.border.TitledBorder;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import org.hibernate.Criteria;
import org.hibernate.Transaction;
import org.hibernate.criterion.MatchMode;
import org.hibernate.criterion.Restrictions;

public class CompanyConfig extends javax.swing.JPanel {

    int selctedRowId;

    private boolean isUpdateable;

    Criteria c = EXTCLASS.getHibSession().createCriteria(MyCompanyDetails.class);

    public CompanyConfig() {
        initComponents();

        comAllList.getTableHeader().setDefaultRenderer(new Sup_VenManagement.HeaderColor());
        loadTbl(c);
        changeLangu();
        jTabbedPane1.setIconAt(0, new ImageIcon(getClass().getResource("/Img/Plus_25px.png")));
        jTabbedPane1.setIconAt(1, new ImageIcon(getClass().getResource("/Img/List_25px.png")));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jLabel_3 = new javax.swing.JLabel();
        com_basic_name = new javax.swing.JTextField();
        jLabel_4 = new javax.swing.JLabel();
        com_basic_br = new javax.swing.JTextField();
        jLabel_2 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        com_basic_logo = new javax.swing.JLabel();
        ppp = new javax.swing.JPanel();
        com_basic_headerIcon = new javax.swing.JLabel();
        jLabel_1 = new javax.swing.JLabel();
        com_basic_btnUp2 = new javax.swing.JLabel();
        com_basic_btnUp1 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jLabel_5 = new javax.swing.JLabel();
        com_ad_no = new javax.swing.JTextField();
        jLabel_6 = new javax.swing.JLabel();
        com_ad_street = new javax.swing.JTextField();
        jLabel_7 = new javax.swing.JLabel();
        com_ad_city = new javax.swing.JTextField();
        jLabel_8 = new javax.swing.JLabel();
        com_ad_country = new javax.swing.JTextField();
        jPanel12 = new javax.swing.JPanel();
        jLabel_9 = new javax.swing.JLabel();
        com_co_mob1 = new javax.swing.JTextField();
        com_co_mob2 = new javax.swing.JTextField();
        jLabel_10 = new javax.swing.JLabel();
        com_con_land2 = new javax.swing.JTextField();
        jLabel_11 = new javax.swing.JLabel();
        com_con_email = new javax.swing.JTextField();
        com_con_web = new javax.swing.JTextField();
        com_con_land1 = new javax.swing.JTextField();
        jLabel_12 = new javax.swing.JLabel();
        com_con_emailPass = new javax.swing.JPasswordField();
        com_con_emailPassShow = new javax.swing.JCheckBox();
        jLabel_13 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        com_btnSave = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        com_btnClear = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        comAllList = new javax.swing.JTable();
        com_btnListUpdate = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        com_btnSetActive = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        com_searchName = new javax.swing.JTextField();
        jLabel_14 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTabbedPane1.setBackground(new java.awt.Color(79, 51, 81));
        jTabbedPane1.setForeground(new java.awt.Color(79, 51, 81));
        jTabbedPane1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jTabbedPane1.setFocusable(false);
        jTabbedPane1.setFont(new java.awt.Font("Nirmala UI", 1, 17)); // NOI18N

        jPanel9.setBackground(new java.awt.Color(68, 50, 72));
        jPanel9.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel10.setBackground(new java.awt.Color(79, 51, 81));
        jPanel10.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED), "BASIC", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Iskoola Pota", 1, 19), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel_3.setFont(new java.awt.Font("Nirmala UI", 0, 17)); // NOI18N
        jLabel_3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_3.setText("Company Name");
        jPanel10.add(jLabel_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, -1, -1));

        com_basic_name.setFont(new java.awt.Font("Nirmala UI", 0, 18)); // NOI18N
        com_basic_name.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel10.add(com_basic_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(248, 340, 360, -1));

        jLabel_4.setFont(new java.awt.Font("Nirmala UI", 0, 17)); // NOI18N
        jLabel_4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_4.setText("Business Registration NO");
        jPanel10.add(jLabel_4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 400, -1, -1));

        com_basic_br.setFont(new java.awt.Font("Nirmala UI", 0, 18)); // NOI18N
        com_basic_br.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel10.add(com_basic_br, new org.netbeans.lib.awtextra.AbsoluteConstraints(248, 400, 360, -1));

        jLabel_2.setFont(new java.awt.Font("Nirmala UI", 0, 17)); // NOI18N
        jLabel_2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_2.setText("Header Icon");
        jPanel10.add(jLabel_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 220, -1, -1));

        jPanel7.setBackground(new java.awt.Color(79, 51, 81));
        jPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel7.add(com_basic_logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 330, 150));

        jPanel10.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, 330, 150));

        ppp.setBackground(new java.awt.Color(79, 51, 81));
        ppp.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        ppp.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        ppp.add(com_basic_headerIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 50));

        jPanel10.add(ppp, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 250, 50, 50));

        jLabel_1.setFont(new java.awt.Font("Nirmala UI", 0, 17)); // NOI18N
        jLabel_1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_1.setText("Company Logo");
        jPanel10.add(jLabel_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, -1, -1));

        com_basic_btnUp2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/btn_upload.png"))); // NOI18N
        com_basic_btnUp2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        com_basic_btnUp2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                com_basic_btnUp2MouseClicked(evt);
            }
        });
        jPanel10.add(com_basic_btnUp2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 250, 80, 50));

        com_basic_btnUp1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/btn_upload.png"))); // NOI18N
        com_basic_btnUp1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        com_basic_btnUp1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                com_basic_btnUp1MouseClicked(evt);
            }
        });
        jPanel10.add(com_basic_btnUp1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 110, 80, 50));

        jPanel9.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 630, 460));

        jPanel11.setBackground(new java.awt.Color(79, 51, 81));
        jPanel11.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED), "ADDRESS", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Iskoola Pota", 1, 19), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel_5.setFont(new java.awt.Font("Nirmala UI", 0, 17)); // NOI18N
        jLabel_5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_5.setText("NO");
        jPanel11.add(jLabel_5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, -1, -1));

        com_ad_no.setFont(new java.awt.Font("Nirmala UI", 0, 18)); // NOI18N
        com_ad_no.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel11.add(com_ad_no, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 60, 350, -1));

        jLabel_6.setFont(new java.awt.Font("Nirmala UI", 0, 17)); // NOI18N
        jLabel_6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_6.setText("Street");
        jPanel11.add(jLabel_6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, -1, -1));

        com_ad_street.setFont(new java.awt.Font("Nirmala UI", 0, 18)); // NOI18N
        com_ad_street.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel11.add(com_ad_street, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 120, 350, -1));

        jLabel_7.setFont(new java.awt.Font("Nirmala UI", 0, 17)); // NOI18N
        jLabel_7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_7.setText("City");
        jPanel11.add(jLabel_7, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 180, -1, -1));

        com_ad_city.setFont(new java.awt.Font("Nirmala UI", 0, 18)); // NOI18N
        com_ad_city.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel11.add(com_ad_city, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 180, 350, -1));

        jLabel_8.setFont(new java.awt.Font("Nirmala UI", 0, 17)); // NOI18N
        jLabel_8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_8.setText("Country");
        jPanel11.add(jLabel_8, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 240, -1, -1));

        com_ad_country.setFont(new java.awt.Font("Nirmala UI", 0, 18)); // NOI18N
        com_ad_country.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel11.add(com_ad_country, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 240, 350, -1));

        jPanel9.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 500, 630, 300));

        jPanel12.setBackground(new java.awt.Color(79, 51, 81));
        jPanel12.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED), "CONTACT", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Iskoola Pota", 1, 19), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel_9.setFont(new java.awt.Font("Nirmala UI", 0, 17)); // NOI18N
        jLabel_9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_9.setText("Mobile NO");
        jPanel12.add(jLabel_9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, -1));

        com_co_mob1.setFont(new java.awt.Font("Nirmala UI", 0, 18)); // NOI18N
        com_co_mob1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        com_co_mob1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                com_co_mob1KeyTyped(evt);
            }
        });
        jPanel12.add(com_co_mob1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 100, 270, -1));

        com_co_mob2.setFont(new java.awt.Font("Nirmala UI", 0, 18)); // NOI18N
        com_co_mob2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        com_co_mob2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                com_co_mob2KeyTyped(evt);
            }
        });
        jPanel12.add(com_co_mob2, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 100, 250, -1));

        jLabel_10.setFont(new java.awt.Font("Nirmala UI", 0, 17)); // NOI18N
        jLabel_10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_10.setText("Land NO");
        jPanel12.add(jLabel_10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, -1, -1));

        com_con_land2.setFont(new java.awt.Font("Nirmala UI", 0, 18)); // NOI18N
        com_con_land2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        com_con_land2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                com_con_land2MouseClicked(evt);
            }
        });
        com_con_land2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                com_con_land2KeyTyped(evt);
            }
        });
        jPanel12.add(com_con_land2, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 160, 250, -1));

        jLabel_11.setFont(new java.awt.Font("Nirmala UI", 0, 17)); // NOI18N
        jLabel_11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_11.setText("Email");
        jPanel12.add(jLabel_11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, -1, -1));

        com_con_email.setFont(new java.awt.Font("Nirmala UI", 0, 18)); // NOI18N
        com_con_email.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel12.add(com_con_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 220, 530, -1));

        com_con_web.setFont(new java.awt.Font("Nirmala UI", 0, 18)); // NOI18N
        com_con_web.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel12.add(com_con_web, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 340, 470, -1));

        com_con_land1.setFont(new java.awt.Font("Nirmala UI", 0, 18)); // NOI18N
        com_con_land1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        com_con_land1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                com_con_land1KeyTyped(evt);
            }
        });
        jPanel12.add(com_con_land1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 160, 270, -1));

        jLabel_12.setFont(new java.awt.Font("Nirmala UI", 0, 17)); // NOI18N
        jLabel_12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_12.setText("Email Password");
        jPanel12.add(jLabel_12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, -1, -1));

        com_con_emailPass.setFont(new java.awt.Font("Nirmala UI", 0, 18)); // NOI18N
        com_con_emailPass.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel12.add(com_con_emailPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 280, 270, -1));

        com_con_emailPassShow.setBackground(new java.awt.Color(79, 51, 81));
        com_con_emailPassShow.setFont(new java.awt.Font("Nirmala UI", 0, 15)); // NOI18N
        com_con_emailPassShow.setForeground(new java.awt.Color(255, 255, 255));
        com_con_emailPassShow.setText("Show");
        com_con_emailPassShow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                com_con_emailPassShowActionPerformed(evt);
            }
        });
        jPanel12.add(com_con_emailPassShow, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 280, -1, -1));

        jLabel_13.setFont(new java.awt.Font("Nirmala UI", 0, 17)); // NOI18N
        jLabel_13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_13.setText("Web Site");
        jPanel12.add(jLabel_13, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/back_browse.png"))); // NOI18N
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        jPanel12.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 330, 50, 50));

        jPanel9.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 30, 780, 450));

        com_btnSave.setFont(new java.awt.Font("Nirmala UI", 1, 18)); // NOI18N
        com_btnSave.setForeground(new java.awt.Color(255, 255, 255));
        com_btnSave.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        com_btnSave.setText("SAVE");
        com_btnSave.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        com_btnSave.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                com_btnSaveMouseClicked(evt);
            }
        });
        jPanel9.add(com_btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 630, 180, 40));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/btn_any.png"))); // NOI18N
        jPanel9.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 630, 200, 50));

        com_btnClear.setFont(new java.awt.Font("Nirmala UI", 1, 18)); // NOI18N
        com_btnClear.setForeground(new java.awt.Color(255, 255, 255));
        com_btnClear.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        com_btnClear.setText("CLEAR");
        com_btnClear.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        com_btnClear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                com_btnClearMouseClicked(evt);
            }
        });
        jPanel9.add(com_btnClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 630, 180, 40));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/btn_any.png"))); // NOI18N
        jPanel9.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 630, 200, 50));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Add New Detail", jPanel2);

        jPanel4.setBackground(new java.awt.Color(68, 50, 72));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel13.setBackground(new java.awt.Color(79, 51, 81));
        jPanel13.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED), "ALL LIST", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Iskoola Pota", 1, 19), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel13.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        comAllList.setBackground(new java.awt.Color(79, 51, 81));
        comAllList.setFont(new java.awt.Font("Nirmala UI", 0, 18)); // NOI18N
        comAllList.setForeground(new java.awt.Color(255, 255, 255));
        comAllList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "BR", "Email", "Web ", "Status"
            }
        ));
        comAllList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                comAllListMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(comAllList);

        jPanel13.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 120, 1270, -1));

        com_btnListUpdate.setFont(new java.awt.Font("Nirmala UI", 1, 17)); // NOI18N
        com_btnListUpdate.setForeground(new java.awt.Color(255, 255, 255));
        com_btnListUpdate.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        com_btnListUpdate.setText("UPDATE");
        com_btnListUpdate.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        com_btnListUpdate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                com_btnListUpdateMouseClicked(evt);
            }
        });
        jPanel13.add(com_btnListUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 618, 250, 40));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/btn_anyLong.png"))); // NOI18N
        jPanel13.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 610, 270, 60));

        com_btnSetActive.setFont(new java.awt.Font("Nirmala UI", 1, 17)); // NOI18N
        com_btnSetActive.setForeground(new java.awt.Color(255, 255, 255));
        com_btnSetActive.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        com_btnSetActive.setText("SET ACTIVE ");
        com_btnSetActive.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        com_btnSetActive.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                com_btnSetActiveMouseClicked(evt);
            }
        });
        jPanel13.add(com_btnSetActive, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 618, 250, 40));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/btn_anyLong.png"))); // NOI18N
        jPanel13.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 610, 260, 60));

        com_searchName.setFont(new java.awt.Font("Nirmala UI", 0, 18)); // NOI18N
        com_searchName.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        com_searchName.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                com_searchNameMouseClicked(evt);
            }
        });
        com_searchName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                com_searchNameKeyReleased(evt);
            }
        });
        jPanel13.add(com_searchName, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 70, 240, -1));

        jLabel_14.setFont(new java.awt.Font("Nirmala UI", 0, 17)); // NOI18N
        jLabel_14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_14.setText("Search By Name");
        jPanel13.add(jLabel_14, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, -1, 50));

        jPanel4.add(jPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 1440, 750));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("All Details", jPanel3);

        jPanel1.add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 1520, 850));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/panelBack_1.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1580, 900));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    MyCompanyDetails company;

    private void com_btnSaveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_com_btnSaveMouseClicked

        try {
            ArrayList<String> err = checkFields();

            //not updateble
            if (err.isEmpty()) {

                if (!isUpdateable) {

                    company = new MyCompanyDetails();
                }
                //save

                company.setImg1(imgpath2);
                company.setImg2(imgpath);
                company.setName(com_basic_name.getText());
                company.setRegNo(com_basic_br.getText());

                company.setNo(com_ad_no.getText());
                company.setStreet(com_ad_street.getText());
                company.setCity(com_ad_city.getText());
                company.setCountry(com_ad_country.getText());

                boolean isInt = false;

                try {

                    if (!com_co_mob1.getText().isEmpty()) {

                        company.setMobile1(Integer.parseInt(com_co_mob1.getText()));
                    }
                    if (!com_co_mob2.getText().isEmpty()) {

                        company.setMobile2(Integer.parseInt(com_co_mob2.getText()));
                    }
                    if (!com_con_land1.getText().isEmpty()) {
                        company.setTp1(Integer.parseInt(com_con_land1.getText()));
                    }
                    if (!com_con_land2.getText().isEmpty()) {
                        company.setTp2(Integer.parseInt(com_con_land2.getText()));
                    }

                    isInt = true;
                } catch (NumberFormatException e) {
                    isInt = false;
                }
                company.setEmail(com_con_email.getText());
                company.setHeading1(com_con_emailPass.getText());
                company.setWebsite(com_con_web.getText());

                if (isInt) {
                    deactiveOthers();

                    company.setStatus("active");

                    if (!isUpdateable) {

                        EXTCLASS.getHibSession().save(company);
                        EXTCLASS.showMessage("Record added!", "දත්ත එක් කළා !", "SUCCESS", Application.SINSUCCESS, 1);

                    } else {
                        EXTCLASS.getHibSession().update(company);
                        EXTCLASS.showMessage("Record updated!", "දත්ත යාවත්කාලීන කරන ලදි !", "SUCCESS", Application.SINSUCCESS, 1);
                    }

                    Transaction t = EXTCLASS.getHibSession().beginTransaction();
                    t.commit();

                    loadTbl(c);
                    clearFields();
                } else {
                    EXTCLASS.showMessage("Enter numbers only!", "අංක පමණක් ඇතුළත් කරන්න", "ERROR", Application.SINERROR, 0);

                }

            } else {
                String erros = "";
                int i = 0;
                for (String e : err) {
                    erros += e;
                    i++;
                    erros += (err.size() != i) ? "," : ".";

                }
                EXTCLASS.showMessage("Fill following fields " + erros, "කරුණාකර පහත දැක්වෙන විස්තර පුරවන්න " + erros, "ERROR", Application.SINERROR, 0);

            }

        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_com_btnSaveMouseClicked
    String imgpath = "";
    String imgpath2 = "";
    private void com_basic_btnUp1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_com_basic_btnUp1MouseClicked

        try {
            JFileChooser jf = new JFileChooser();
            int x = jf.showOpenDialog(this);
            if (x == jf.APPROVE_OPTION) {
                File f = jf.getSelectedFile();
                String path = f.getAbsolutePath();
                imgpath = path.replace("\\", "/");
                f = new File(imgpath);
                Image img = ImageIO.read(f);
                img = img.getScaledInstance(com_basic_logo.getWidth(), com_basic_logo.getHeight(), Image.SCALE_SMOOTH);
                com_basic_logo.setIcon(new ImageIcon(img));

            }

        } catch (Exception e) {
            e.printStackTrace();
        }

    }//GEN-LAST:event_com_basic_btnUp1MouseClicked

    private void com_basic_btnUp2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_com_basic_btnUp2MouseClicked
        try {
            JFileChooser jf = new JFileChooser();
            int x = jf.showOpenDialog(this);
            if (x == jf.APPROVE_OPTION) {
                File f = jf.getSelectedFile();
                String path = f.getAbsolutePath();
                imgpath2 = path.replace("\\", "/");
                f = new File(imgpath2);
                Image img = ImageIO.read(f);
                img = img.getScaledInstance(com_basic_headerIcon.getWidth(), com_basic_headerIcon.getHeight(), Image.SCALE_SMOOTH);
                com_basic_headerIcon.setIcon(new ImageIcon(img));

            }

        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_com_basic_btnUp2MouseClicked

    private void com_con_emailPassShowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_com_con_emailPassShowActionPerformed
        if (com_con_emailPassShow.isSelected()) {
            com_con_emailPass.setEchoChar((char) 0);
        } else {
            com_con_emailPass.setEchoChar('*');
        }

    }//GEN-LAST:event_com_con_emailPassShowActionPerformed

    private void comAllListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_comAllListMouseClicked
        try {

            selctedRowId = (int) comAllList.getValueAt(comAllList.getSelectedRow(), 0);
            System.out.println(selctedRowId);

        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_comAllListMouseClicked

    private void com_btnSetActiveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_com_btnSetActiveMouseClicked
        try {
            JLabel msg = new JLabel();
            String header = "";

            msg.setFont(new Font("Iskoola Pota", Font.PLAIN, 18));
            if (Application.getLangu().equals("SIN")) {
                header = Application.SININFO;
                msg.setText("ඔබට විශ්වාසයිද ?");
            } else {
                header = "INFO";
                msg.setText("Are you sure ?");
            }

            if (selctedRowId != 0) {

                if (JOptionPane.showConfirmDialog(this, msg, header, JOptionPane.WARNING_MESSAGE) == 0) {

                    company = (MyCompanyDetails) EXTCLASS.getHibSession().load(MyCompanyDetails.class, selctedRowId);
                    deactiveOthers();
                    company.setStatus("active");

                    EXTCLASS.getHibSession().update(company);

                    Transaction t = EXTCLASS.getHibSession().beginTransaction();
                    t.commit();

                    loadTbl(c);
                }

            } else {

                EXTCLASS.showMessage("Please select the row!", "කරුණාකර පේළියක් තෝරන්න"
                        + "", "WARNING", Application.SINWARN, 2);
            }

        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_com_btnSetActiveMouseClicked

    private void com_searchNameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_com_searchNameMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_com_searchNameMouseClicked

    private void com_searchNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_com_searchNameKeyReleased
        try {

            Criteria c = EXTCLASS.getHibSession().createCriteria(MyCompanyDetails.class);
            c.add(Restrictions.like("name", com_searchName.getText(), MatchMode.ANYWHERE));
            loadTbl(c);

        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_com_searchNameKeyReleased

    private void com_btnListUpdateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_com_btnListUpdateMouseClicked
        try {
            clearFields();
            isUpdateable = true;

            if (selctedRowId != 0) {

                company = (MyCompanyDetails) EXTCLASS.getHibSession().load(MyCompanyDetails.class, selctedRowId);

                if (!company.getImg1().isEmpty()) {

                    imgpath2 = company.getImg1();
                    Image img = ImageIO.read(new File(company.getImg1()));
                    img = img.getScaledInstance(com_basic_headerIcon.getWidth(), com_basic_headerIcon.getHeight(), Image.SCALE_SMOOTH);
                    com_basic_headerIcon.setIcon(new ImageIcon(img));
                }
                if (!company.getImg2().isEmpty()) {

                    imgpath = company.getImg2();
                    Image img = ImageIO.read(new File(company.getImg2()));
                    img = img.getScaledInstance(com_basic_logo.getWidth(), com_basic_logo.getHeight(), Image.SCALE_SMOOTH);
                    com_basic_logo.setIcon(new ImageIcon(img));
                }

                com_basic_name.setText(company.getName());
                com_basic_br.setText(company.getRegNo());
                com_ad_no.setText(company.getNo());
                com_ad_street.setText(company.getStreet());
                com_ad_city.setText(company.getCity());
                com_ad_country.setText(company.getCountry());

                if (company.getMobile1() != null) {
                    com_co_mob1.setText(company.getMobile1().toString());
                }
                if (company.getMobile2() != null) {

                    com_co_mob2.setText(company.getMobile2().toString());
                }
                if (company.getTp1() != null) {

                    com_con_land1.setText(company.getTp1().toString());
                }
                if (company.getTp2() != null) {

                    com_con_land2.setText(company.getTp2().toString());
                }
                com_con_email.setText(company.getEmail());
                com_con_emailPass.setText(company.getHeading1());
                com_con_web.setText(company.getWebsite());

                jTabbedPane1.setSelectedIndex(0);

            } else {
                EXTCLASS.showMessage("Please select the row!", "කරුණාකර පේළියක් තෝරන්න"
                        + "", "WARNING", Application.SINWARN, 2);
            }

        } catch (Exception e) {
            e.printStackTrace();
        }

    }//GEN-LAST:event_com_btnListUpdateMouseClicked

    private void com_btnClearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_com_btnClearMouseClicked
        clearFields();

        changeLangu();
    }//GEN-LAST:event_com_btnClearMouseClicked

    private void com_co_mob1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_com_co_mob1KeyTyped

        if (!Character.isDigit(evt.getKeyChar())) {

            evt.consume();
        }
        if (com_co_mob1.getText().length() >= 15) {
            evt.consume();
        }


    }//GEN-LAST:event_com_co_mob1KeyTyped

    private void com_co_mob2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_com_co_mob2KeyTyped
        if (!Character.isDigit(evt.getKeyChar())) {

            evt.consume();
        }
        if (com_co_mob2.getText().length() >= 15) {
            evt.consume();
        }
    }//GEN-LAST:event_com_co_mob2KeyTyped

    private void com_con_land1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_com_con_land1KeyTyped
        if (!Character.isDigit(evt.getKeyChar())) {

            evt.consume();
        }
        if (com_con_land1.getText().length() >= 15) {
            evt.consume();
        }
    }//GEN-LAST:event_com_con_land1KeyTyped

    private void com_con_land2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_com_con_land2MouseClicked

    }//GEN-LAST:event_com_con_land2MouseClicked

    private void com_con_land2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_com_con_land2KeyTyped
        if (!Character.isDigit(evt.getKeyChar())) {

            evt.consume();
        }
        if (com_con_land2.getText().length() >= 15) {
            evt.consume();
        }
    }//GEN-LAST:event_com_con_land2KeyTyped

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked

        Desktop d = Desktop.getDesktop();
        try {
            if (!com_con_web.getText().isEmpty()) {

                d.browse(new URI(com_con_web.getText()));//http://google.com
            }

        } catch (IOException | URISyntaxException e2) {

            EXTCLASS.showMessage("Wrong web address!", "වැරදි වෙබ් ලිපිනයක් ", "ERROR", Application.SINERROR, 0);

            e2.printStackTrace();

        }
    }//GEN-LAST:event_jLabel2MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable comAllList;
    private javax.swing.JTextField com_ad_city;
    private javax.swing.JTextField com_ad_country;
    private javax.swing.JTextField com_ad_no;
    private javax.swing.JTextField com_ad_street;
    private javax.swing.JTextField com_basic_br;
    private javax.swing.JLabel com_basic_btnUp1;
    private javax.swing.JLabel com_basic_btnUp2;
    private javax.swing.JLabel com_basic_headerIcon;
    private javax.swing.JLabel com_basic_logo;
    private javax.swing.JTextField com_basic_name;
    private static javax.swing.JLabel com_btnClear;
    private static javax.swing.JLabel com_btnListUpdate;
    private static javax.swing.JLabel com_btnSave;
    private static javax.swing.JLabel com_btnSetActive;
    private javax.swing.JTextField com_co_mob1;
    private javax.swing.JTextField com_co_mob2;
    private javax.swing.JTextField com_con_email;
    private javax.swing.JPasswordField com_con_emailPass;
    private static javax.swing.JCheckBox com_con_emailPassShow;
    private javax.swing.JTextField com_con_land1;
    private javax.swing.JTextField com_con_land2;
    private javax.swing.JTextField com_con_web;
    private javax.swing.JTextField com_searchName;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private static javax.swing.JLabel jLabel_1;
    private static javax.swing.JLabel jLabel_10;
    private static javax.swing.JLabel jLabel_11;
    private static javax.swing.JLabel jLabel_12;
    private static javax.swing.JLabel jLabel_13;
    private static javax.swing.JLabel jLabel_14;
    private static javax.swing.JLabel jLabel_2;
    private static javax.swing.JLabel jLabel_3;
    private static javax.swing.JLabel jLabel_4;
    private static javax.swing.JLabel jLabel_5;
    private static javax.swing.JLabel jLabel_6;
    private static javax.swing.JLabel jLabel_7;
    private static javax.swing.JLabel jLabel_8;
    private static javax.swing.JLabel jLabel_9;
    private javax.swing.JPanel jPanel1;
    private static javax.swing.JPanel jPanel10;
    private static javax.swing.JPanel jPanel11;
    private static javax.swing.JPanel jPanel12;
    private static javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private static javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JPanel ppp;
    // End of variables declaration//GEN-END:variables

    private ArrayList<String> checkFields() {

        ArrayList<String> err = new ArrayList<>();
        if (com_basic_name.getText().isEmpty()) {
            err.add(jLabel_3.getText());
        }
        if (com_ad_no.getText().isEmpty()) {
            err.add(jLabel_5.getText());
        }
        if (com_ad_street.getText().isEmpty()) {
            err.add(jLabel_6.getText());
        }
        if (com_ad_city.getText().isEmpty()) {
            err.add(jLabel_7.getText());
        }
        if (com_ad_country.getText().isEmpty()) {
            err.add(jLabel_8.getText());
        }
        if (com_co_mob1.getText().isEmpty() && com_co_mob2.getText().isEmpty()) {
            err.add(jLabel_9.getText());
        }
        if (com_con_land1.getText().isEmpty() && com_con_land2.getText().isEmpty()) {
            err.add(jLabel_10.getText());
        }
        return err;
    }

    private void clearFields() {

        isUpdateable = false;

        imgpath = "";
        imgpath2 = "";

        com_basic_logo.setIcon(null);
        com_basic_headerIcon.setIcon(null);
        com_basic_name.setText(null);
        com_basic_br.setText(null);

        com_ad_no.setText(null);
        com_ad_street.setText(null);
        com_ad_city.setText(null);
        com_ad_country.setText(null);

        com_co_mob1.setText(null);
        com_co_mob2.setText(null);
        com_con_land1.setText(null);
        com_con_land2.setText(null);
        com_con_email.setText(null);
        com_con_emailPass.setText(null);
        com_con_web.setText(null);
    }

    private void loadTbl(Criteria c) {

        try {

            DefaultTableModel dtm = (DefaultTableModel) comAllList.getModel();
            dtm.setRowCount(0);

            if (!c.list().isEmpty()) {

                List<MyCompanyDetails> list = c.list();

                for (MyCompanyDetails myCompanyDetails : list) {
                    Vector v = new Vector();
                    v.add(myCompanyDetails.getIdcompanyDetails());
                    v.add(myCompanyDetails.getName());
                    v.add(myCompanyDetails.getRegNo());
                    v.add(myCompanyDetails.getEmail());
                    v.add(myCompanyDetails.getWebsite());
                    v.add(myCompanyDetails.getStatus());
                    dtm.addRow(v);
                }

            }
        } catch (Exception e) {
            e.printStackTrace();
        }

    }

    private void deactiveOthers() {

        try {

            //deactive all other records
            Criteria c = EXTCLASS.getHibSession().createCriteria(MyCompanyDetails.class);
            if (!c.list().isEmpty()) {

                List<MyCompanyDetails> list = c.list();

                for (MyCompanyDetails myCompanyDetails : list) {

                    myCompanyDetails.setStatus("deactive");

                    EXTCLASS.getHibSession().update(myCompanyDetails);
                }

            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    public static void changeLangu() {

        if (Application.getLangu().equals("SIN")) {

            jLabel_1.setText("සමාගමේ ලාංඡනය");
            jLabel_2.setText("ශීර්ෂක අයිකනය");
            jLabel_3.setText("සමාගම් නාමය");
            jLabel_4.setText("ව්‍යාපාර ලියාපදිංචි අංකය");
            jLabel_5.setText("නො");
            jLabel_6.setText("වීදිය");
            jLabel_7.setText("නගරය");
            jLabel_8.setText("රට");
            jLabel_9.setText("ජංගම දු :අ ");
            jLabel_10.setText("දුරකථන අංකය");
            jLabel_11.setText("විද්‍යුත් තැපෑල");
            jLabel_12.setText("විද්‍යුත් තැපෑල් මුරපදය");
            jLabel_13.setText("වෙබ් අඩවිය");
            jLabel_14.setText("නම අනුව සෙවීම");

            com_con_emailPassShow.setText("පෙන්වන්න");

            com_btnSave.setText("සුරකින්න");
            com_btnClear.setText("මකන්න");

            com_btnListUpdate.setText("යාවත්කාලීන කරන්න");
            com_btnSetActive.setText("ක්‍රියාත්මක කරන්න");

            TitledBorder t1 = BorderFactory.createTitledBorder(new SoftBevelBorder(0));
            t1.setTitle("මූලික තොරතුරු");
            t1.setTitleColor(Color.WHITE);
            t1.setTitleFont(new Font("Nirmala UI", Font.BOLD, 17));

            TitledBorder t2 = BorderFactory.createTitledBorder(new SoftBevelBorder(0));
            t2.setTitle("ඇමතුම් විස්තර");
            t2.setTitleColor(Color.WHITE);
            t2.setTitleFont(new Font("Nirmala UI", Font.BOLD, 17));

            TitledBorder t3 = BorderFactory.createTitledBorder(new SoftBevelBorder(0));
            t3.setTitle("ලිපිනය විස්තර");
            t3.setTitleColor(Color.WHITE);
            t3.setTitleFont(new Font("Nirmala UI", Font.BOLD, 17));

            TitledBorder t4 = BorderFactory.createTitledBorder(new SoftBevelBorder(0));
            t4.setTitle("ලැයිස්තුව");
            t4.setTitleColor(Color.WHITE);
            t4.setTitleFont(new Font("Nirmala UI", Font.BOLD, 17));

            jPanel10.setBorder(t1);
            jPanel12.setBorder(t2);
            jPanel11.setBorder(t3);
            jPanel13.setBorder(t4);

            jTabbedPane1.setTitleAt(0, "එක් කරන්න");
            jTabbedPane1.setTitleAt(1, "මුළු ලැයිස්තුව");
        } else {

            jLabel_1.setText("Company Logo");
            jLabel_2.setText("Header Icon");
            jLabel_3.setText("Company Name");
            jLabel_4.setText("Business Registration NO");
            jLabel_5.setText("NO");
            jLabel_6.setText("Street");
            jLabel_7.setText("City");
            jLabel_8.setText("Country");
            jLabel_9.setText("Mobile");
            jLabel_10.setText("Land NO");
            jLabel_11.setText("Email");
            jLabel_12.setText("Email Password");
            jLabel_13.setText("Website");
            jLabel_14.setText("Search by name");

            com_con_emailPassShow.setText("Show");

            com_btnSave.setText("SAVE");
            com_btnClear.setText("CLEAR");

            com_btnListUpdate.setText("UPDATE");
            com_btnSetActive.setText("SET ACTIVE");

            jPanel10.setBorder(BorderFactory.createTitledBorder(""));
            jPanel12.setBorder(BorderFactory.createTitledBorder(""));
            jPanel11.setBorder(BorderFactory.createTitledBorder(""));

            TitledBorder t1 = BorderFactory.createTitledBorder(new SoftBevelBorder(0));
            t1.setTitle("Basic Details");
            t1.setTitleColor(Color.WHITE);
            t1.setTitleFont(new Font("Nirmala UI", Font.BOLD, 17));

            TitledBorder t2 = BorderFactory.createTitledBorder(new SoftBevelBorder(0));
            t2.setTitle("Contact Details");
            t2.setTitleColor(Color.WHITE);
            t2.setTitleFont(new Font("Nirmala UI", Font.BOLD, 17));

            TitledBorder t3 = BorderFactory.createTitledBorder(new SoftBevelBorder(0));
            t3.setTitle("Address Details");
            t3.setTitleColor(Color.WHITE);
            t3.setTitleFont(new Font("Nirmala UI", Font.BOLD, 17));

            TitledBorder t4 = BorderFactory.createTitledBorder(new SoftBevelBorder(0));
            t4.setTitle("List");
            t4.setTitleColor(Color.WHITE);
            t4.setTitleFont(new Font("Nirmala UI", Font.BOLD, 17));

            jPanel10.setBorder(t1);
            jPanel12.setBorder(t2);
            jPanel11.setBorder(t3);
            jPanel13.setBorder(t4);

            jTabbedPane1.setTitleAt(0, "ADD DETAILS");
            jTabbedPane1.setTitleAt(1, "ALL LIST");

        }
    }

    public static class HeaderColor extends DefaultTableCellRenderer {

        public HeaderColor() {
            setFont(new Font("Nirmala UI", Font.BOLD, 20));
            setOpaque(true);

        }

        @Override
        public Component getTableCellRendererComponent(JTable table, Object value,
                boolean isSelected, boolean hasFocus, int row, int column) {
            setText(value.toString());
            setBackground(new Color(70, 45, 70));
            setForeground(Color.white);
            return this;
        }

    }
}
