/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Panels;

import Classes.Application;
import Classes.EXTCLASS;
import Pojos.Employee;
import UI.Login;
import java.awt.Font;
import java.util.Random;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import org.hibernate.Criteria;
import org.hibernate.criterion.Restrictions;

/**
 *
 * @author Sheha
 */
public class Forgot_password extends javax.swing.JPanel {

    public Forgot_password() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        empEmail_txt = new javax.swing.JTextField();
        empId_txt1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        empMobile_txt = new javax.swing.JTextField();
        result = new javax.swing.JLabel();
        sendMessage_btn = new javax.swing.JLabel();
        check_btn = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        codeNo_txt = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        sendEmail_btn = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        jPanel2.setBackground(new java.awt.Color(63, 45, 67));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Lock_35px_1.png"))); // NOI18N
        jLabel1.setToolTipText("Login?");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 500, 40, 40));

        jLabel4.setFont(new java.awt.Font("Century Gothic", 1, 22)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(115, 52, 108));
        jLabel4.setText("EMP ID");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 123, -1, 30));

        empEmail_txt.setBackground(new java.awt.Color(64, 47, 66));
        empEmail_txt.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        empEmail_txt.setForeground(new java.awt.Color(204, 204, 204));
        empEmail_txt.setBorder(null);
        empEmail_txt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                empEmail_txtMouseClicked(evt);
            }
        });
        empEmail_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empEmail_txtActionPerformed(evt);
            }
        });
        jPanel2.add(empEmail_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 180, 230, 30));

        empId_txt1.setBackground(new java.awt.Color(64, 47, 66));
        empId_txt1.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        empId_txt1.setForeground(new java.awt.Color(204, 204, 204));
        empId_txt1.setBorder(null);
        empId_txt1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                empId_txt1MouseClicked(evt);
            }
        });
        empId_txt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empId_txt1ActionPerformed(evt);
            }
        });
        empId_txt1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                empId_txt1KeyTyped(evt);
            }
        });
        jPanel2.add(empId_txt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 120, 230, 30));

        jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 22)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(115, 52, 108));
        jLabel3.setText("EMAIL");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, -1, 30));
        jPanel2.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 150, 230, 20));
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 210, 230, 30));
        jPanel2.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 270, 230, 30));

        empMobile_txt.setBackground(new java.awt.Color(64, 47, 66));
        empMobile_txt.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        empMobile_txt.setForeground(new java.awt.Color(204, 204, 204));
        empMobile_txt.setBorder(null);
        empMobile_txt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                empMobile_txtMouseClicked(evt);
            }
        });
        empMobile_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empMobile_txtActionPerformed(evt);
            }
        });
        empMobile_txt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                empMobile_txtKeyTyped(evt);
            }
        });
        jPanel2.add(empMobile_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 240, 230, 30));

        result.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        result.setForeground(new java.awt.Color(115, 52, 108));
        jPanel2.add(result, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 470, 350, 40));

        sendMessage_btn.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        sendMessage_btn.setForeground(new java.awt.Color(174, 53, 158));
        sendMessage_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Phone Message_50px.png"))); // NOI18N
        sendMessage_btn.setText("SEND MESSAGE");
        sendMessage_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        sendMessage_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                sendMessage_btnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                sendMessage_btnMouseExited(evt);
            }
        });
        jPanel2.add(sendMessage_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 300, 220, 90));

        check_btn.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        check_btn.setForeground(new java.awt.Color(174, 53, 158));
        check_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Checked Checkbox_35px.png"))); // NOI18N
        check_btn.setToolTipText("Check Code");
        check_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        check_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                check_btnMouseClicked(evt);
            }
        });
        jPanel2.add(check_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 410, 40, 40));
        jPanel2.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 440, 170, 20));

        codeNo_txt.setEditable(false);
        codeNo_txt.setBackground(new java.awt.Color(64, 47, 66));
        codeNo_txt.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        codeNo_txt.setForeground(new java.awt.Color(204, 204, 204));
        codeNo_txt.setBorder(null);
        codeNo_txt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                codeNo_txtMouseClicked(evt);
            }
        });
        codeNo_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codeNo_txtActionPerformed(evt);
            }
        });
        jPanel2.add(codeNo_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 410, 170, 30));

        jLabel8.setFont(new java.awt.Font("Century Gothic", 1, 22)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(115, 52, 108));
        jLabel8.setText("MOBILE");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, -1, 30));

        sendEmail_btn.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        sendEmail_btn.setForeground(new java.awt.Color(174, 53, 158));
        sendEmail_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Send_50px.png"))); // NOI18N
        sendEmail_btn.setText("SEND EMAIL");
        sendEmail_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        sendEmail_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sendEmail_btnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                sendEmail_btnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                sendEmail_btnMouseExited(evt);
            }
        });
        jPanel2.add(sendEmail_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, 200, 90));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/forgotPw.jpg"))); // NOI18N
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 476, 539));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked

        EXTCLASS.FrameAdd(new Sign_In(), Login.card_login);

        Thread t2 = new Thread() {
            public void run() {

                EXTCLASS.playClip(Login.audiioPath, this);

            }
        };

        t2.start();

    }//GEN-LAST:event_jLabel1MouseClicked

    private void empEmail_txtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_empEmail_txtMouseClicked
        empEmail_txt.setText(null);
    }//GEN-LAST:event_empEmail_txtMouseClicked

    private void empEmail_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empEmail_txtActionPerformed
        empMobile_txt.grabFocus();

    }//GEN-LAST:event_empEmail_txtActionPerformed

    private void empId_txt1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_empId_txt1MouseClicked
        empId_txt1.setText(null);
    }//GEN-LAST:event_empId_txt1MouseClicked

    private void empId_txt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empId_txt1ActionPerformed
        empEmail_txt.grabFocus();
    }//GEN-LAST:event_empId_txt1ActionPerformed

    private void empMobile_txtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_empMobile_txtMouseClicked
        empMobile_txt.setText(null);
    }//GEN-LAST:event_empMobile_txtMouseClicked

    private void empMobile_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empMobile_txtActionPerformed
        codeNo_txt.grabFocus();
    }//GEN-LAST:event_empMobile_txtActionPerformed

    private void codeNo_txtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_codeNo_txtMouseClicked
        codeNo_txt.setText(null);
    }//GEN-LAST:event_codeNo_txtMouseClicked

    private void codeNo_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codeNo_txtActionPerformed
        Thread t = new Thread() {
            public void run() {
                checkCode();

            }
        };
        Thread t2 = new Thread() {
            public void run() {

                EXTCLASS.playClip(Login.audiioPath, this);

            }
        };
        t.start();
        t2.start();
    }//GEN-LAST:event_codeNo_txtActionPerformed

    private void sendMessage_btnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sendMessage_btnMouseEntered

        sendMessage_btn.setIcon(new ImageIcon(getClass().getResource("/Img/Phone Message_80px.png")));
        sendMessage_btn.setFont(new Font("Century Gothic", Font.PLAIN, 18));


    }//GEN-LAST:event_sendMessage_btnMouseEntered

    private void sendMessage_btnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sendMessage_btnMouseExited

        sendMessage_btn.setIcon(new ImageIcon(getClass().getResource("/Img/Phone Message_50px.png")));
        sendMessage_btn.setFont(new Font("Century Gothic", Font.PLAIN, 16));

    }//GEN-LAST:event_sendMessage_btnMouseExited

    private void sendEmail_btnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sendEmail_btnMouseEntered

        sendEmail_btn.setIcon(new ImageIcon(getClass().getResource("/Img/Send_80px.png")));
        sendEmail_btn.setFont(new Font("Century Gothic", Font.PLAIN, 18));


    }//GEN-LAST:event_sendEmail_btnMouseEntered

    private void sendEmail_btnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sendEmail_btnMouseExited

        sendEmail_btn.setIcon(new ImageIcon(getClass().getResource("/Img/Send_50px.png")));
        sendEmail_btn.setFont(new Font("Century Gothic", Font.PLAIN, 16));


    }//GEN-LAST:event_sendEmail_btnMouseExited

    private void sendEmail_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sendEmail_btnMouseClicked

        Thread t = new Thread() {
            public void run() {
                sendEmail();

            }
        };
        Thread t2 = new Thread() {
            public void run() {

                EXTCLASS.playClip(Login.audiioPath, this);

            }
        };
        t.start();
        t2.start();


    }//GEN-LAST:event_sendEmail_btnMouseClicked

    private void empId_txt1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_empId_txt1KeyTyped
        if (!Character.isDigit(evt.getKeyChar())) {

            evt.consume();
        }
        if (empId_txt1.getText().length() >= 10) {
            evt.consume();
        }
    }//GEN-LAST:event_empId_txt1KeyTyped

    private void empMobile_txtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_empMobile_txtKeyTyped
        if (!Character.isDigit(evt.getKeyChar())) {

            evt.consume();
        }
        if (empMobile_txt.getText().length() >= 15) {
            evt.consume();
        }
    }//GEN-LAST:event_empMobile_txtKeyTyped

    private void check_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_check_btnMouseClicked
        Thread t = new Thread() {
            public void run() {
                checkCode();

            }
        };
        Thread t2 = new Thread() {
            public void run() {

                EXTCLASS.playClip(Login.audiioPath, this);

            }
        };
        t.start();
        t2.start();

    }//GEN-LAST:event_check_btnMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel check_btn;
    private javax.swing.JTextField codeNo_txt;
    private javax.swing.JTextField empEmail_txt;
    private javax.swing.JTextField empId_txt1;
    private javax.swing.JTextField empMobile_txt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JLabel result;
    private javax.swing.JLabel sendEmail_btn;
    private javax.swing.JLabel sendMessage_btn;
    // End of variables declaration//GEN-END:variables
  public String getSaltString() {
        String SALTCHARS = "ABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890abcdefghijklmnopqrstuvwxyz";
        StringBuilder salt = new StringBuilder();
        Random rnd = new Random();
        while (salt.length() < 6) { // length of the random string.
            int index = (int) (rnd.nextFloat() * SALTCHARS.length());
            salt.append(SALTCHARS.charAt(index));
        }
        String saltStr = salt.toString();
        return saltStr;

    }

    String code;
    String password;

    private void sendEmail() {
        try {
            if (!empEmail_txt.getText().isEmpty() && !empId_txt1.getText().isEmpty() && !empMobile_txt.getText().isEmpty()) {

                Criteria c = EXTCLASS.getHibSession().createCriteria(Employee.class);

                boolean isNumber;
                try {

                    c.add(Restrictions.eq("idemployee", Integer.parseInt(empId_txt1.getText())));
                    c.add(Restrictions.eq("email", empEmail_txt.getText()));
                    c.add(Restrictions.eq("mobile", Integer.parseInt(empMobile_txt.getText())));
                    isNumber = true;
                } catch (NumberFormatException e) {

                    isNumber = false;
                }
                if (isNumber) {

                    if (!c.list().isEmpty()) {

                        Employee e = (Employee) c.uniqueResult();
                        String code_ = getSaltString();
                        code = code_;
                        System.out.println(code);
                        //!x
                        if (EXTCLASS.sendMail(e.getEmail(), Application.getCompany().getName() + " System", "Hello " + e.getName() + ", your password verification code is - " + code)) {
                            password = e.getPassword();

                            JOptionPane.showMessageDialog(this, "Email sent to " + e.getEmail());
                            codeNo_txt.setEditable(true);
                        } else {

                            JOptionPane.showMessageDialog(this, "Email sending failed!");
                        }

                    } else {

                        JOptionPane.showMessageDialog(this, "No matching details!");
                    }

                } else {
                    JOptionPane.showMessageDialog(this, "Please enter numbers only!");
                }
            } else {

                JOptionPane.showMessageDialog(this, "Fill the details!");
            }
        } catch (Exception e) {
            e.printStackTrace();
        }

    }

    private void checkCode() {
        try {
            if (!codeNo_txt.getText().isEmpty()) {

                if (codeNo_txt.getText().equals(code)) {

                    result.setText("Your password is - " + password);
                } else {
                    JOptionPane.showMessageDialog(this, "Wrong code number!");
                }
            } else {
                JOptionPane.showMessageDialog(this, "Fill the details!");
            }

        } catch (Exception e) {
            e.printStackTrace();
        }
    }
}
