package Pojos;
// Generated Nov 13, 2018 10:52:25 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Customer generated by hbm2java
 */
public class Customer  implements java.io.Serializable {


     private Integer idcustomer;
     private String name;
     private Set<InvoiceCus> invoiceCuses = new HashSet<InvoiceCus>(0);
     private Set<CusReturn> cusReturns = new HashSet<CusReturn>(0);

    public Customer() {
    }

    public Customer(String name, Set<InvoiceCus> invoiceCuses, Set<CusReturn> cusReturns) {
       this.name = name;
       this.invoiceCuses = invoiceCuses;
       this.cusReturns = cusReturns;
    }
   
    public Integer getIdcustomer() {
        return this.idcustomer;
    }
    
    public void setIdcustomer(Integer idcustomer) {
        this.idcustomer = idcustomer;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Set<InvoiceCus> getInvoiceCuses() {
        return this.invoiceCuses;
    }
    
    public void setInvoiceCuses(Set<InvoiceCus> invoiceCuses) {
        this.invoiceCuses = invoiceCuses;
    }
    public Set<CusReturn> getCusReturns() {
        return this.cusReturns;
    }
    
    public void setCusReturns(Set<CusReturn> cusReturns) {
        this.cusReturns = cusReturns;
    }




}


