package Pojos;
// Generated Nov 13, 2018 10:52:25 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Employee generated by hbm2java
 */
public class Employee  implements java.io.Serializable {


     private int idemployee;
     private EmployeeType employeeType;
     private MyCompanyDetails myCompanyDetails;
     private String name;
     private String username;
     private String email;
     private String password;
     private Integer mobile;
     private String img;
     private String qr;
     private String status;
     private Set<Login> logins = new HashSet<Login>(0);
     private Set<Privileges> privilegeses = new HashSet<Privileges>(0);

    public Employee() {
    }

	
    public Employee(int idemployee, EmployeeType employeeType, MyCompanyDetails myCompanyDetails) {
        this.idemployee = idemployee;
        this.employeeType = employeeType;
        this.myCompanyDetails = myCompanyDetails;
    }
    public Employee(int idemployee, EmployeeType employeeType, MyCompanyDetails myCompanyDetails, String name, String username, String email, String password, Integer mobile, String img, String qr, String status, Set<Login> logins, Set<Privileges> privilegeses) {
       this.idemployee = idemployee;
       this.employeeType = employeeType;
       this.myCompanyDetails = myCompanyDetails;
       this.name = name;
       this.username = username;
       this.email = email;
       this.password = password;
       this.mobile = mobile;
       this.img = img;
       this.qr = qr;
       this.status = status;
       this.logins = logins;
       this.privilegeses = privilegeses;
    }
   
    public int getIdemployee() {
        return this.idemployee;
    }
    
    public void setIdemployee(int idemployee) {
        this.idemployee = idemployee;
    }
    public EmployeeType getEmployeeType() {
        return this.employeeType;
    }
    
    public void setEmployeeType(EmployeeType employeeType) {
        this.employeeType = employeeType;
    }
    public MyCompanyDetails getMyCompanyDetails() {
        return this.myCompanyDetails;
    }
    
    public void setMyCompanyDetails(MyCompanyDetails myCompanyDetails) {
        this.myCompanyDetails = myCompanyDetails;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public Integer getMobile() {
        return this.mobile;
    }
    
    public void setMobile(Integer mobile) {
        this.mobile = mobile;
    }
    public String getImg() {
        return this.img;
    }
    
    public void setImg(String img) {
        this.img = img;
    }
    public String getQr() {
        return this.qr;
    }
    
    public void setQr(String qr) {
        this.qr = qr;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    public Set<Login> getLogins() {
        return this.logins;
    }
    
    public void setLogins(Set<Login> logins) {
        this.logins = logins;
    }
    public Set<Privileges> getPrivilegeses() {
        return this.privilegeses;
    }
    
    public void setPrivilegeses(Set<Privileges> privilegeses) {
        this.privilegeses = privilegeses;
    }




}


