package Pojos;
// Generated Nov 13, 2018 10:52:25 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * EmployeeType generated by hbm2java
 */
public class EmployeeType  implements java.io.Serializable {


     private Integer idemployeeType;
     private String type;
     private Set<Employee> employees = new HashSet<Employee>(0);

    public EmployeeType() {
    }

    public EmployeeType(String type, Set<Employee> employees) {
       this.type = type;
       this.employees = employees;
    }
   
    public Integer getIdemployeeType() {
        return this.idemployeeType;
    }
    
    public void setIdemployeeType(Integer idemployeeType) {
        this.idemployeeType = idemployeeType;
    }
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }
    public Set<Employee> getEmployees() {
        return this.employees;
    }
    
    public void setEmployees(Set<Employee> employees) {
        this.employees = employees;
    }




}


