package Pojos;
// Generated Nov 13, 2018 10:52:25 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Grn generated by hbm2java
 */
public class Grn  implements java.io.Serializable {


     private Integer idgrn;
     private Supplier supplier;
     private Date date;
     private Date time;
     private Date dueDate;
     private Date dueTime;
     private String paymentMethod;
     private Double total;
     private Double discount;
     private Double tax;
     private Double other;
     private Double payment;
     private Double balance;
     private String status;
     private Set<GrnHasItems> grnHasItemses = new HashSet<GrnHasItems>(0);

    public Grn() {
    }

	
    public Grn(Supplier supplier) {
        this.supplier = supplier;
    }
    public Grn(Supplier supplier, Date date, Date time, Date dueDate, Date dueTime, String paymentMethod, Double total, Double discount, Double tax, Double other, Double payment, Double balance, String status, Set<GrnHasItems> grnHasItemses) {
       this.supplier = supplier;
       this.date = date;
       this.time = time;
       this.dueDate = dueDate;
       this.dueTime = dueTime;
       this.paymentMethod = paymentMethod;
       this.total = total;
       this.discount = discount;
       this.tax = tax;
       this.other = other;
       this.payment = payment;
       this.balance = balance;
       this.status = status;
       this.grnHasItemses = grnHasItemses;
    }
   
    public Integer getIdgrn() {
        return this.idgrn;
    }
    
    public void setIdgrn(Integer idgrn) {
        this.idgrn = idgrn;
    }
    public Supplier getSupplier() {
        return this.supplier;
    }
    
    public void setSupplier(Supplier supplier) {
        this.supplier = supplier;
    }
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }
    public Date getTime() {
        return this.time;
    }
    
    public void setTime(Date time) {
        this.time = time;
    }
    public Date getDueDate() {
        return this.dueDate;
    }
    
    public void setDueDate(Date dueDate) {
        this.dueDate = dueDate;
    }
    public Date getDueTime() {
        return this.dueTime;
    }
    
    public void setDueTime(Date dueTime) {
        this.dueTime = dueTime;
    }
    public String getPaymentMethod() {
        return this.paymentMethod;
    }
    
    public void setPaymentMethod(String paymentMethod) {
        this.paymentMethod = paymentMethod;
    }
    public Double getTotal() {
        return this.total;
    }
    
    public void setTotal(Double total) {
        this.total = total;
    }
    public Double getDiscount() {
        return this.discount;
    }
    
    public void setDiscount(Double discount) {
        this.discount = discount;
    }
    public Double getTax() {
        return this.tax;
    }
    
    public void setTax(Double tax) {
        this.tax = tax;
    }
    public Double getOther() {
        return this.other;
    }
    
    public void setOther(Double other) {
        this.other = other;
    }
    public Double getPayment() {
        return this.payment;
    }
    
    public void setPayment(Double payment) {
        this.payment = payment;
    }
    public Double getBalance() {
        return this.balance;
    }
    
    public void setBalance(Double balance) {
        this.balance = balance;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    public Set<GrnHasItems> getGrnHasItemses() {
        return this.grnHasItemses;
    }
    
    public void setGrnHasItemses(Set<GrnHasItems> grnHasItemses) {
        this.grnHasItemses = grnHasItemses;
    }




}


