package Pojos;
// Generated Nov 13, 2018 10:52:25 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * InvoiceHasItemsCus generated by hbm2java
 */
public class InvoiceHasItemsCus  implements java.io.Serializable {


     private Integer idinvoiceHasItems;
     private InvoiceCus invoiceCus;
     private Stock stock;
     private Date date;
     private Date time;
     private Double qty;
     private Double subTot;
     private Double discount;
     private Double tax;
     private Double tot;
     private String status;
     private Set<CusReturn> cusReturns = new HashSet<CusReturn>(0);

    public InvoiceHasItemsCus() {
    }

	
    public InvoiceHasItemsCus(InvoiceCus invoiceCus, Stock stock) {
        this.invoiceCus = invoiceCus;
        this.stock = stock;
    }
    public InvoiceHasItemsCus(InvoiceCus invoiceCus, Stock stock, Date date, Date time, Double qty, Double subTot, Double discount, Double tax, Double tot, String status, Set<CusReturn> cusReturns) {
       this.invoiceCus = invoiceCus;
       this.stock = stock;
       this.date = date;
       this.time = time;
       this.qty = qty;
       this.subTot = subTot;
       this.discount = discount;
       this.tax = tax;
       this.tot = tot;
       this.status = status;
       this.cusReturns = cusReturns;
    }
   
    public Integer getIdinvoiceHasItems() {
        return this.idinvoiceHasItems;
    }
    
    public void setIdinvoiceHasItems(Integer idinvoiceHasItems) {
        this.idinvoiceHasItems = idinvoiceHasItems;
    }
    public InvoiceCus getInvoiceCus() {
        return this.invoiceCus;
    }
    
    public void setInvoiceCus(InvoiceCus invoiceCus) {
        this.invoiceCus = invoiceCus;
    }
    public Stock getStock() {
        return this.stock;
    }
    
    public void setStock(Stock stock) {
        this.stock = stock;
    }
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }
    public Date getTime() {
        return this.time;
    }
    
    public void setTime(Date time) {
        this.time = time;
    }
    public Double getQty() {
        return this.qty;
    }
    
    public void setQty(Double qty) {
        this.qty = qty;
    }
    public Double getSubTot() {
        return this.subTot;
    }
    
    public void setSubTot(Double subTot) {
        this.subTot = subTot;
    }
    public Double getDiscount() {
        return this.discount;
    }
    
    public void setDiscount(Double discount) {
        this.discount = discount;
    }
    public Double getTax() {
        return this.tax;
    }
    
    public void setTax(Double tax) {
        this.tax = tax;
    }
    public Double getTot() {
        return this.tot;
    }
    
    public void setTot(Double tot) {
        this.tot = tot;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    public Set<CusReturn> getCusReturns() {
        return this.cusReturns;
    }
    
    public void setCusReturns(Set<CusReturn> cusReturns) {
        this.cusReturns = cusReturns;
    }




}


