package Pojos;
// Generated Nov 13, 2018 10:52:25 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * InvoiceHasItemsVen generated by hbm2java
 */
public class InvoiceHasItemsVen  implements java.io.Serializable {


     private Integer idinvoiceHasItemsVen;
     private InvoiceVen invoiceVen;
     private Stock stock;
     private Date date;
     private Date time;
     private Double qty;
     private Double subTot;
     private Double discount;
     private Double tax;
     private Double tot;
     private String status;
     private Set<VendorReturn> vendorReturns = new HashSet<VendorReturn>(0);

    public InvoiceHasItemsVen() {
    }

	
    public InvoiceHasItemsVen(InvoiceVen invoiceVen, Stock stock) {
        this.invoiceVen = invoiceVen;
        this.stock = stock;
    }
    public InvoiceHasItemsVen(InvoiceVen invoiceVen, Stock stock, Date date, Date time, Double qty, Double subTot, Double discount, Double tax, Double tot, String status, Set<VendorReturn> vendorReturns) {
       this.invoiceVen = invoiceVen;
       this.stock = stock;
       this.date = date;
       this.time = time;
       this.qty = qty;
       this.subTot = subTot;
       this.discount = discount;
       this.tax = tax;
       this.tot = tot;
       this.status = status;
       this.vendorReturns = vendorReturns;
    }
   
    public Integer getIdinvoiceHasItemsVen() {
        return this.idinvoiceHasItemsVen;
    }
    
    public void setIdinvoiceHasItemsVen(Integer idinvoiceHasItemsVen) {
        this.idinvoiceHasItemsVen = idinvoiceHasItemsVen;
    }
    public InvoiceVen getInvoiceVen() {
        return this.invoiceVen;
    }
    
    public void setInvoiceVen(InvoiceVen invoiceVen) {
        this.invoiceVen = invoiceVen;
    }
    public Stock getStock() {
        return this.stock;
    }
    
    public void setStock(Stock stock) {
        this.stock = stock;
    }
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }
    public Date getTime() {
        return this.time;
    }
    
    public void setTime(Date time) {
        this.time = time;
    }
    public Double getQty() {
        return this.qty;
    }
    
    public void setQty(Double qty) {
        this.qty = qty;
    }
    public Double getSubTot() {
        return this.subTot;
    }
    
    public void setSubTot(Double subTot) {
        this.subTot = subTot;
    }
    public Double getDiscount() {
        return this.discount;
    }
    
    public void setDiscount(Double discount) {
        this.discount = discount;
    }
    public Double getTax() {
        return this.tax;
    }
    
    public void setTax(Double tax) {
        this.tax = tax;
    }
    public Double getTot() {
        return this.tot;
    }
    
    public void setTot(Double tot) {
        this.tot = tot;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    public Set<VendorReturn> getVendorReturns() {
        return this.vendorReturns;
    }
    
    public void setVendorReturns(Set<VendorReturn> vendorReturns) {
        this.vendorReturns = vendorReturns;
    }




}


