package Pojos;
// Generated Nov 13, 2018 10:52:25 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * InvoiceVen generated by hbm2java
 */
public class InvoiceVen  implements java.io.Serializable {


     private Integer idinvoiceVen;
     private Vendor vendor;
     private Date date;
     private Date time;
     private Date dueDate;
     private Date dueTime;
     private Double subTot;
     private Double discount;
     private Double tax;
     private Double tot;
     private Double payment;
     private Double balance;
     private String status;
     private Set<InvoiceHasItemsVen> invoiceHasItemsVens = new HashSet<InvoiceHasItemsVen>(0);

    public InvoiceVen() {
    }

	
    public InvoiceVen(Vendor vendor) {
        this.vendor = vendor;
    }
    public InvoiceVen(Vendor vendor, Date date, Date time, Date dueDate, Date dueTime, Double subTot, Double discount, Double tax, Double tot, Double payment, Double balance, String status, Set<InvoiceHasItemsVen> invoiceHasItemsVens) {
       this.vendor = vendor;
       this.date = date;
       this.time = time;
       this.dueDate = dueDate;
       this.dueTime = dueTime;
       this.subTot = subTot;
       this.discount = discount;
       this.tax = tax;
       this.tot = tot;
       this.payment = payment;
       this.balance = balance;
       this.status = status;
       this.invoiceHasItemsVens = invoiceHasItemsVens;
    }
   
    public Integer getIdinvoiceVen() {
        return this.idinvoiceVen;
    }
    
    public void setIdinvoiceVen(Integer idinvoiceVen) {
        this.idinvoiceVen = idinvoiceVen;
    }
    public Vendor getVendor() {
        return this.vendor;
    }
    
    public void setVendor(Vendor vendor) {
        this.vendor = vendor;
    }
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }
    public Date getTime() {
        return this.time;
    }
    
    public void setTime(Date time) {
        this.time = time;
    }
    public Date getDueDate() {
        return this.dueDate;
    }
    
    public void setDueDate(Date dueDate) {
        this.dueDate = dueDate;
    }
    public Date getDueTime() {
        return this.dueTime;
    }
    
    public void setDueTime(Date dueTime) {
        this.dueTime = dueTime;
    }
    public Double getSubTot() {
        return this.subTot;
    }
    
    public void setSubTot(Double subTot) {
        this.subTot = subTot;
    }
    public Double getDiscount() {
        return this.discount;
    }
    
    public void setDiscount(Double discount) {
        this.discount = discount;
    }
    public Double getTax() {
        return this.tax;
    }
    
    public void setTax(Double tax) {
        this.tax = tax;
    }
    public Double getTot() {
        return this.tot;
    }
    
    public void setTot(Double tot) {
        this.tot = tot;
    }
    public Double getPayment() {
        return this.payment;
    }
    
    public void setPayment(Double payment) {
        this.payment = payment;
    }
    public Double getBalance() {
        return this.balance;
    }
    
    public void setBalance(Double balance) {
        this.balance = balance;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    public Set<InvoiceHasItemsVen> getInvoiceHasItemsVens() {
        return this.invoiceHasItemsVens;
    }
    
    public void setInvoiceHasItemsVens(Set<InvoiceHasItemsVen> invoiceHasItemsVens) {
        this.invoiceHasItemsVens = invoiceHasItemsVens;
    }




}


