package Pojos;
// Generated Nov 13, 2018 10:52:25 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * MyCompanyDetails generated by hbm2java
 */
public class MyCompanyDetails  implements java.io.Serializable {


     private Integer idcompanyDetails;
     private String name;
     private String no;
     private String street;
     private String city;
     private String country;
     private Integer mobile1;
     private Integer mobile2;
     private Integer tp1;
     private Integer tp2;
     private String email;
     private String website;
     private String regNo;
     private String heading1;
     private String heading2;
     private String heading3;
     private String img1;
     private String img2;
     private String img3;
     private String useEmail;
     private String status;
     private Set<Employee> employees = new HashSet<Employee>(0);

    public MyCompanyDetails() {
    }

    public MyCompanyDetails(String name, String no, String street, String city, String country, Integer mobile1, Integer mobile2, Integer tp1, Integer tp2, String email, String website, String regNo, String heading1, String heading2, String heading3, String img1, String img2, String img3, String useEmail, String status, Set<Employee> employees) {
       this.name = name;
       this.no = no;
       this.street = street;
       this.city = city;
       this.country = country;
       this.mobile1 = mobile1;
       this.mobile2 = mobile2;
       this.tp1 = tp1;
       this.tp2 = tp2;
       this.email = email;
       this.website = website;
       this.regNo = regNo;
       this.heading1 = heading1;
       this.heading2 = heading2;
       this.heading3 = heading3;
       this.img1 = img1;
       this.img2 = img2;
       this.img3 = img3;
       this.useEmail = useEmail;
       this.status = status;
       this.employees = employees;
    }
   
    public Integer getIdcompanyDetails() {
        return this.idcompanyDetails;
    }
    
    public void setIdcompanyDetails(Integer idcompanyDetails) {
        this.idcompanyDetails = idcompanyDetails;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getNo() {
        return this.no;
    }
    
    public void setNo(String no) {
        this.no = no;
    }
    public String getStreet() {
        return this.street;
    }
    
    public void setStreet(String street) {
        this.street = street;
    }
    public String getCity() {
        return this.city;
    }
    
    public void setCity(String city) {
        this.city = city;
    }
    public String getCountry() {
        return this.country;
    }
    
    public void setCountry(String country) {
        this.country = country;
    }
    public Integer getMobile1() {
        return this.mobile1;
    }
    
    public void setMobile1(Integer mobile1) {
        this.mobile1 = mobile1;
    }
    public Integer getMobile2() {
        return this.mobile2;
    }
    
    public void setMobile2(Integer mobile2) {
        this.mobile2 = mobile2;
    }
    public Integer getTp1() {
        return this.tp1;
    }
    
    public void setTp1(Integer tp1) {
        this.tp1 = tp1;
    }
    public Integer getTp2() {
        return this.tp2;
    }
    
    public void setTp2(Integer tp2) {
        this.tp2 = tp2;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getWebsite() {
        return this.website;
    }
    
    public void setWebsite(String website) {
        this.website = website;
    }
    public String getRegNo() {
        return this.regNo;
    }
    
    public void setRegNo(String regNo) {
        this.regNo = regNo;
    }
    public String getHeading1() {
        return this.heading1;
    }
    
    public void setHeading1(String heading1) {
        this.heading1 = heading1;
    }
    public String getHeading2() {
        return this.heading2;
    }
    
    public void setHeading2(String heading2) {
        this.heading2 = heading2;
    }
    public String getHeading3() {
        return this.heading3;
    }
    
    public void setHeading3(String heading3) {
        this.heading3 = heading3;
    }
    public String getImg1() {
        return this.img1;
    }
    
    public void setImg1(String img1) {
        this.img1 = img1;
    }
    public String getImg2() {
        return this.img2;
    }
    
    public void setImg2(String img2) {
        this.img2 = img2;
    }
    public String getImg3() {
        return this.img3;
    }
    
    public void setImg3(String img3) {
        this.img3 = img3;
    }
    public String getUseEmail() {
        return this.useEmail;
    }
    
    public void setUseEmail(String useEmail) {
        this.useEmail = useEmail;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    public Set<Employee> getEmployees() {
        return this.employees;
    }
    
    public void setEmployees(Set<Employee> employees) {
        this.employees = employees;
    }




}


