package Pojos;
// Generated Nov 13, 2018 10:52:25 PM by Hibernate Tools 4.3.1



/**
 * Privileges generated by hbm2java
 */
public class Privileges  implements java.io.Serializable {


     private Integer idprivileges;
     private Employee employee;
     private String uiName;
     private String action;
     private Boolean state;
     private String status;

    public Privileges() {
    }

	
    public Privileges(Employee employee) {
        this.employee = employee;
    }
    public Privileges(Employee employee, String uiName, String action, Boolean state, String status) {
       this.employee = employee;
       this.uiName = uiName;
       this.action = action;
       this.state = state;
       this.status = status;
    }
   
    public Integer getIdprivileges() {
        return this.idprivileges;
    }
    
    public void setIdprivileges(Integer idprivileges) {
        this.idprivileges = idprivileges;
    }
    public Employee getEmployee() {
        return this.employee;
    }
    
    public void setEmployee(Employee employee) {
        this.employee = employee;
    }
    public String getUiName() {
        return this.uiName;
    }
    
    public void setUiName(String uiName) {
        this.uiName = uiName;
    }
    public String getAction() {
        return this.action;
    }
    
    public void setAction(String action) {
        this.action = action;
    }
    public Boolean getState() {
        return this.state;
    }
    
    public void setState(Boolean state) {
        this.state = state;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }




}


