package Pojos;
// Generated Nov 13, 2018 10:52:25 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Product generated by hbm2java
 */
public class Product  implements java.io.Serializable {


     private String idproduct;
     private ProductBrand productBrand;
     private ProductType productType;
     private Unit unit;
     private String name;
     private String itemType;
     private String qr;
     private String img;
     private String status;
     private Set<Stock> stocks = new HashSet<Stock>(0);

    public Product() {
    }

	
    public Product(String idproduct, ProductBrand productBrand, ProductType productType, Unit unit) {
        this.idproduct = idproduct;
        this.productBrand = productBrand;
        this.productType = productType;
        this.unit = unit;
    }
    public Product(String idproduct, ProductBrand productBrand, ProductType productType, Unit unit, String name, String itemType, String qr, String img, String status, Set<Stock> stocks) {
       this.idproduct = idproduct;
       this.productBrand = productBrand;
       this.productType = productType;
       this.unit = unit;
       this.name = name;
       this.itemType = itemType;
       this.qr = qr;
       this.img = img;
       this.status = status;
       this.stocks = stocks;
    }
   
    public String getIdproduct() {
        return this.idproduct;
    }
    
    public void setIdproduct(String idproduct) {
        this.idproduct = idproduct;
    }
    public ProductBrand getProductBrand() {
        return this.productBrand;
    }
    
    public void setProductBrand(ProductBrand productBrand) {
        this.productBrand = productBrand;
    }
    public ProductType getProductType() {
        return this.productType;
    }
    
    public void setProductType(ProductType productType) {
        this.productType = productType;
    }
    public Unit getUnit() {
        return this.unit;
    }
    
    public void setUnit(Unit unit) {
        this.unit = unit;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getItemType() {
        return this.itemType;
    }
    
    public void setItemType(String itemType) {
        this.itemType = itemType;
    }
    public String getQr() {
        return this.qr;
    }
    
    public void setQr(String qr) {
        this.qr = qr;
    }
    public String getImg() {
        return this.img;
    }
    
    public void setImg(String img) {
        this.img = img;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    public Set<Stock> getStocks() {
        return this.stocks;
    }
    
    public void setStocks(Set<Stock> stocks) {
        this.stocks = stocks;
    }




}


