package Pojos;
// Generated Nov 13, 2018 10:52:25 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * ProductType generated by hbm2java
 */
public class ProductType  implements java.io.Serializable {


     private Integer idproductType;
     private String type;
     private Set<Product> products = new HashSet<Product>(0);

    public ProductType() {
    }

    public ProductType(String type, Set<Product> products) {
       this.type = type;
       this.products = products;
    }
   
    public Integer getIdproductType() {
        return this.idproductType;
    }
    
    public void setIdproductType(Integer idproductType) {
        this.idproductType = idproductType;
    }
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }
    public Set<Product> getProducts() {
        return this.products;
    }
    
    public void setProducts(Set<Product> products) {
        this.products = products;
    }




}


