package Pojos;
// Generated Nov 13, 2018 10:52:25 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Stock generated by hbm2java
 */
public class Stock  implements java.io.Serializable {


     private Integer idstock;
     private Product product;
     private Date addDate;
     private Date expDate;
     private Double availableQty;
     private Double unitPrice;
     private Double unitSellingPrice;
     private Double discount;
     private Double tax;
     private String qr;
     private String img;
     private String status;
     private Set<ReturnToSupplier> returnToSuppliers = new HashSet<ReturnToSupplier>(0);
     private Set<InvoiceHasItemsVen> invoiceHasItemsVens = new HashSet<InvoiceHasItemsVen>(0);
     private Set<GrnHasItems> grnHasItemses = new HashSet<GrnHasItems>(0);
     private Set<InvoiceHasItemsCus> invoiceHasItemsCuses = new HashSet<InvoiceHasItemsCus>(0);

    public Stock() {
    }

	
    public Stock(Product product) {
        this.product = product;
    }
    public Stock(Product product, Date addDate, Date expDate, Double availableQty, Double unitPrice, Double unitSellingPrice, Double discount, Double tax, String qr, String img, String status, Set<ReturnToSupplier> returnToSuppliers, Set<InvoiceHasItemsVen> invoiceHasItemsVens, Set<GrnHasItems> grnHasItemses, Set<InvoiceHasItemsCus> invoiceHasItemsCuses) {
       this.product = product;
       this.addDate = addDate;
       this.expDate = expDate;
       this.availableQty = availableQty;
       this.unitPrice = unitPrice;
       this.unitSellingPrice = unitSellingPrice;
       this.discount = discount;
       this.tax = tax;
       this.qr = qr;
       this.img = img;
       this.status = status;
       this.returnToSuppliers = returnToSuppliers;
       this.invoiceHasItemsVens = invoiceHasItemsVens;
       this.grnHasItemses = grnHasItemses;
       this.invoiceHasItemsCuses = invoiceHasItemsCuses;
    }
   
    public Integer getIdstock() {
        return this.idstock;
    }
    
    public void setIdstock(Integer idstock) {
        this.idstock = idstock;
    }
    public Product getProduct() {
        return this.product;
    }
    
    public void setProduct(Product product) {
        this.product = product;
    }
    public Date getAddDate() {
        return this.addDate;
    }
    
    public void setAddDate(Date addDate) {
        this.addDate = addDate;
    }
    public Date getExpDate() {
        return this.expDate;
    }
    
    public void setExpDate(Date expDate) {
        this.expDate = expDate;
    }
    public Double getAvailableQty() {
        return this.availableQty;
    }
    
    public void setAvailableQty(Double availableQty) {
        this.availableQty = availableQty;
    }
    public Double getUnitPrice() {
        return this.unitPrice;
    }
    
    public void setUnitPrice(Double unitPrice) {
        this.unitPrice = unitPrice;
    }
    public Double getUnitSellingPrice() {
        return this.unitSellingPrice;
    }
    
    public void setUnitSellingPrice(Double unitSellingPrice) {
        this.unitSellingPrice = unitSellingPrice;
    }
    public Double getDiscount() {
        return this.discount;
    }
    
    public void setDiscount(Double discount) {
        this.discount = discount;
    }
    public Double getTax() {
        return this.tax;
    }
    
    public void setTax(Double tax) {
        this.tax = tax;
    }
    public String getQr() {
        return this.qr;
    }
    
    public void setQr(String qr) {
        this.qr = qr;
    }
    public String getImg() {
        return this.img;
    }
    
    public void setImg(String img) {
        this.img = img;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    public Set<ReturnToSupplier> getReturnToSuppliers() {
        return this.returnToSuppliers;
    }
    
    public void setReturnToSuppliers(Set<ReturnToSupplier> returnToSuppliers) {
        this.returnToSuppliers = returnToSuppliers;
    }
    public Set<InvoiceHasItemsVen> getInvoiceHasItemsVens() {
        return this.invoiceHasItemsVens;
    }
    
    public void setInvoiceHasItemsVens(Set<InvoiceHasItemsVen> invoiceHasItemsVens) {
        this.invoiceHasItemsVens = invoiceHasItemsVens;
    }
    public Set<GrnHasItems> getGrnHasItemses() {
        return this.grnHasItemses;
    }
    
    public void setGrnHasItemses(Set<GrnHasItems> grnHasItemses) {
        this.grnHasItemses = grnHasItemses;
    }
    public Set<InvoiceHasItemsCus> getInvoiceHasItemsCuses() {
        return this.invoiceHasItemsCuses;
    }
    
    public void setInvoiceHasItemsCuses(Set<InvoiceHasItemsCus> invoiceHasItemsCuses) {
        this.invoiceHasItemsCuses = invoiceHasItemsCuses;
    }




}


