package Pojos;
// Generated Nov 13, 2018 10:52:25 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Supplier generated by hbm2java
 */
public class Supplier  implements java.io.Serializable {


     private Integer idsupplier;
     private SupAndVendorCompanyDetails supAndVendorCompanyDetails;
     private String name;
     private Integer mobile;
     private String email;
     private String qr;
     private String img;
     private String status;
     private Set<ReturnToSupplier> returnToSuppliers = new HashSet<ReturnToSupplier>(0);
     private Set<Grn> grns = new HashSet<Grn>(0);

    public Supplier() {
    }

	
    public Supplier(SupAndVendorCompanyDetails supAndVendorCompanyDetails) {
        this.supAndVendorCompanyDetails = supAndVendorCompanyDetails;
    }
    public Supplier(SupAndVendorCompanyDetails supAndVendorCompanyDetails, String name, Integer mobile, String email, String qr, String img, String status, Set<ReturnToSupplier> returnToSuppliers, Set<Grn> grns) {
       this.supAndVendorCompanyDetails = supAndVendorCompanyDetails;
       this.name = name;
       this.mobile = mobile;
       this.email = email;
       this.qr = qr;
       this.img = img;
       this.status = status;
       this.returnToSuppliers = returnToSuppliers;
       this.grns = grns;
    }
   
    public Integer getIdsupplier() {
        return this.idsupplier;
    }
    
    public void setIdsupplier(Integer idsupplier) {
        this.idsupplier = idsupplier;
    }
    public SupAndVendorCompanyDetails getSupAndVendorCompanyDetails() {
        return this.supAndVendorCompanyDetails;
    }
    
    public void setSupAndVendorCompanyDetails(SupAndVendorCompanyDetails supAndVendorCompanyDetails) {
        this.supAndVendorCompanyDetails = supAndVendorCompanyDetails;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Integer getMobile() {
        return this.mobile;
    }
    
    public void setMobile(Integer mobile) {
        this.mobile = mobile;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getQr() {
        return this.qr;
    }
    
    public void setQr(String qr) {
        this.qr = qr;
    }
    public String getImg() {
        return this.img;
    }
    
    public void setImg(String img) {
        this.img = img;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    public Set<ReturnToSupplier> getReturnToSuppliers() {
        return this.returnToSuppliers;
    }
    
    public void setReturnToSuppliers(Set<ReturnToSupplier> returnToSuppliers) {
        this.returnToSuppliers = returnToSuppliers;
    }
    public Set<Grn> getGrns() {
        return this.grns;
    }
    
    public void setGrns(Set<Grn> grns) {
        this.grns = grns;
    }




}


