package Pojos;
// Generated Nov 13, 2018 10:52:25 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Unit generated by hbm2java
 */
public class Unit  implements java.io.Serializable {


     private Integer idunit;
     private String unit;
     private String description;
     private Set<Product> products = new HashSet<Product>(0);

    public Unit() {
    }

    public Unit(String unit, String description, Set<Product> products) {
       this.unit = unit;
       this.description = description;
       this.products = products;
    }
   
    public Integer getIdunit() {
        return this.idunit;
    }
    
    public void setIdunit(Integer idunit) {
        this.idunit = idunit;
    }
    public String getUnit() {
        return this.unit;
    }
    
    public void setUnit(String unit) {
        this.unit = unit;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public Set<Product> getProducts() {
        return this.products;
    }
    
    public void setProducts(Set<Product> products) {
        this.products = products;
    }




}


