package Pojos;
// Generated Nov 13, 2018 10:52:25 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Vendor generated by hbm2java
 */
public class Vendor  implements java.io.Serializable {


     private Integer idvendor;
     private SupAndVendorCompanyDetails supAndVendorCompanyDetails;
     private String name;
     private Integer mobile;
     private String email;
     private String qr;
     private String img;
     private String status;
     private Set<InvoiceVen> invoiceVens = new HashSet<InvoiceVen>(0);
     private Set<VendorReturn> vendorReturns = new HashSet<VendorReturn>(0);

    public Vendor() {
    }

	
    public Vendor(SupAndVendorCompanyDetails supAndVendorCompanyDetails) {
        this.supAndVendorCompanyDetails = supAndVendorCompanyDetails;
    }
    public Vendor(SupAndVendorCompanyDetails supAndVendorCompanyDetails, String name, Integer mobile, String email, String qr, String img, String status, Set<InvoiceVen> invoiceVens, Set<VendorReturn> vendorReturns) {
       this.supAndVendorCompanyDetails = supAndVendorCompanyDetails;
       this.name = name;
       this.mobile = mobile;
       this.email = email;
       this.qr = qr;
       this.img = img;
       this.status = status;
       this.invoiceVens = invoiceVens;
       this.vendorReturns = vendorReturns;
    }
   
    public Integer getIdvendor() {
        return this.idvendor;
    }
    
    public void setIdvendor(Integer idvendor) {
        this.idvendor = idvendor;
    }
    public SupAndVendorCompanyDetails getSupAndVendorCompanyDetails() {
        return this.supAndVendorCompanyDetails;
    }
    
    public void setSupAndVendorCompanyDetails(SupAndVendorCompanyDetails supAndVendorCompanyDetails) {
        this.supAndVendorCompanyDetails = supAndVendorCompanyDetails;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Integer getMobile() {
        return this.mobile;
    }
    
    public void setMobile(Integer mobile) {
        this.mobile = mobile;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getQr() {
        return this.qr;
    }
    
    public void setQr(String qr) {
        this.qr = qr;
    }
    public String getImg() {
        return this.img;
    }
    
    public void setImg(String img) {
        this.img = img;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    public Set<InvoiceVen> getInvoiceVens() {
        return this.invoiceVens;
    }
    
    public void setInvoiceVens(Set<InvoiceVen> invoiceVens) {
        this.invoiceVens = invoiceVens;
    }
    public Set<VendorReturn> getVendorReturns() {
        return this.vendorReturns;
    }
    
    public void setVendorReturns(Set<VendorReturn> vendorReturns) {
        this.vendorReturns = vendorReturns;
    }




}


