package Pojos;
// Generated Nov 13, 2018 10:52:25 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * VendorReturn generated by hbm2java
 */
public class VendorReturn  implements java.io.Serializable {


     private Integer idvendorReturn;
     private InvoiceHasItemsVen invoiceHasItemsVen;
     private Vendor vendor;
     private Date date;
     private Date time;
     private String reason;
     private Double returnQty;
     private Double returnPrice;
     private String status;

    public VendorReturn() {
    }

	
    public VendorReturn(InvoiceHasItemsVen invoiceHasItemsVen, Vendor vendor) {
        this.invoiceHasItemsVen = invoiceHasItemsVen;
        this.vendor = vendor;
    }
    public VendorReturn(InvoiceHasItemsVen invoiceHasItemsVen, Vendor vendor, Date date, Date time, String reason, Double returnQty, Double returnPrice, String status) {
       this.invoiceHasItemsVen = invoiceHasItemsVen;
       this.vendor = vendor;
       this.date = date;
       this.time = time;
       this.reason = reason;
       this.returnQty = returnQty;
       this.returnPrice = returnPrice;
       this.status = status;
    }
   
    public Integer getIdvendorReturn() {
        return this.idvendorReturn;
    }
    
    public void setIdvendorReturn(Integer idvendorReturn) {
        this.idvendorReturn = idvendorReturn;
    }
    public InvoiceHasItemsVen getInvoiceHasItemsVen() {
        return this.invoiceHasItemsVen;
    }
    
    public void setInvoiceHasItemsVen(InvoiceHasItemsVen invoiceHasItemsVen) {
        this.invoiceHasItemsVen = invoiceHasItemsVen;
    }
    public Vendor getVendor() {
        return this.vendor;
    }
    
    public void setVendor(Vendor vendor) {
        this.vendor = vendor;
    }
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }
    public Date getTime() {
        return this.time;
    }
    
    public void setTime(Date time) {
        this.time = time;
    }
    public String getReason() {
        return this.reason;
    }
    
    public void setReason(String reason) {
        this.reason = reason;
    }
    public Double getReturnQty() {
        return this.returnQty;
    }
    
    public void setReturnQty(Double returnQty) {
        this.returnQty = returnQty;
    }
    public Double getReturnPrice() {
        return this.returnPrice;
    }
    
    public void setReturnPrice(Double returnPrice) {
        this.returnPrice = returnPrice;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }




}


